/*
 Navicat Premium Data Transfer

 Source Server         : localPG
 Source Server Type    : PostgreSQL
 Source Server Version : 120004
 Source Host           : localhost:5433
 Source Catalog        : stdb
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 120004
 File Encoding         : 65001

 Date: 09/01/2022 16:39:29
*/


-- ----------------------------
-- Table structure for polygon_persil
-- ----------------------------
DROP TABLE IF EXISTS "public"."polygon_persil";
CREATE TABLE "public"."polygon_persil" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CYCLE
),
  "geom" "public"."geometry",
  "area" float8,
  "created_at" timestamptz(6),
  "updated_at" timestamptz(6)
)
;
ALTER TABLE "public"."polygon_persil" OWNER TO "postgres";

-- ----------------------------
-- Primary Key structure for table polygon_persil
-- ----------------------------
ALTER TABLE "public"."polygon_persil" ADD CONSTRAINT "polygon_persil_pkey" PRIMARY KEY ("id");
